### ISSUE TITLE
Why are you mkdir /bootloader ? 

### ISSUE THREAD

**Issue by Niap** [fraxalotl/SwitchScript#2]
In unix-like system ,it need sudo , and then I think you want to write current direction instead of root direction's bootloader dir?

**Comment by fraxalotl** [comment]
> In unix-like system ,it need sudo , and then I think you want to write current direction instead of root direction's bootloader dir?

Sorry, I really haven't had time to work on this any further, but the script is designed to be ran from the sd card, so thats why I wrote the script making the bootloader file at root dir, but this may be incorrect syntax / directory handling.

It may well need sudo, but at current I haven't had time to look into how sudo interacts with bash.

I kind of started bashing this script together hurredly in my spare time, so I can't lie, it's a very rough draft from someone who doesn't know bash very well haha.

I'll have to investigate when I get more time or maybe someone with more knowledge may be able to create a pull request with better syntax.
